### DISCUSSION TITLE
Turn monitors off when leaving room or lights turned off

### DISCUSSION THREAD

**Discussion by D3SOX** [davidedmundson/kiot#16] [Show and tell]
I think this project is very helpful and can even help to save some energy.
I created a very simple automation that turns off the monitors when leaving the room or turning off the lights.

config
```ini
[Scripts][myScript1]
Exec=/home/nico/scripts/screens-off-wayland.sh
```
script
```bash
#!/usr/bin/env bash
/bin/dbus-send --session --print-reply --dest=org.kde.kglobalaccel /component/org_kde_powerdevil org.kde.kglobalaccel.Component.invokeShortcut string:'Turn Off Screen'
```

automation
```yaml
alias: PC screens off when room lights off or left desk
triggers:
  - trigger: state
    entity_id:
      - light.lights_my_room
    to: "off"
    from: "on"
    id: lights_off
    for:
      hours: 0
      minutes: 0
      seconds: 1
  - trigger: state
    entity_id:
      - binary_sensor.presence_desk
    id: clear
    from: "on"
    to: "off"
    for:
      hours: 0
      minutes: 0
      seconds: 15
conditions:
  - condition: state
    entity_id: binary_sensor.nico_pc_connected
    state: "on"
    alias: If nico-pc is connected
actions:
  - alias: If active wait for inactive, then turn screens off
    if:
      - condition: state
        entity_id: binary_sensor.nico_pc_active
        state: "on"
        alias: If nico-pc is active
    then:
      - wait_for_trigger:
          - trigger: state
            entity_id:
              - binary_sensor.nico_pc_active
            to: "off"
            for:
              hours: 0
              minutes: 0
              seconds: 1
        continue_on_timeout: false
        timeout:
          hours: 0
          minutes: 3
          seconds: 0
          milliseconds: 0
        alias: Wait for 1s inactivity (timeout 2min)
      - action: button.press
        target:
          entity_id: button.nico_pc_turn_screens_off
    else:
      - action: button.press
        target:
          entity_id: button.nico_pc_turn_screens_off
mode: restart
```

**Comment by TheOddPirate** [comment]
Just a small update for triggering shortcuts, this has now become possible with the shortcuts integration and can be used like this =)

```
action: select.select_option
metadata: {}
data:
  option: org_kde_powerdevil - Turn Off Screen
target:
  entity_id: select.n0tgames_shortcuts

```

every global shortcuts should be accessible from this select entity, even from flatpak
