### DISCUSSION TITLE
Similar project

### DISCUSSION THREAD

**Discussion by russellmilliner** [davidedmundson/kiot#6] [General]
This project appears to be very similar to https://github.com/bkbilly/lnxlink  
Is there intention to differentiate this project?
being able to use and manage this with a gui accessible from the app tray would simplify the configuration.  I know this is at very early stage.

**Comment by davidedmundson** [comment]
That's a good link. Thanks. I'll try it and maybe chuck this in the bin. I don't need more projects :)

At a first glance t core is well designed. The desktop level integration is a bit weak; there's a lot that's x11 specific that won't work on Wayland.

Imho it falls into the trap of exposing things for the sake of exposing things, but even so it's still got a lot more than this repo does.

**Reply by D3SOX** [reply]
I have now also looked at this project and I think it's well architected too. (Except the installation part could be better than just a shell script. I should create an AUR package for it.)

Yeah, it exposes a lot of stuff by default but by going through the list of modules and only loading the ones you need you get a pretty minimal footprint.

Now onto porting the KDE specific features of this project to LXLink :eyes:

**Reply by davidedmundson** [reply]
It doesn't work for me unfortunately. I did a little breakdown:

| Feature                     | Status/Comment                                      |
|-----------------------------|-----------------------------------------------------|
| Shutdown                   | got                                                 |
| CPU                        | meh                                                 |
| Restart                    | got                                                 |
| RAM                        | meh                                                 |
| Suspend                    | got                                                 |
| GPU                        | meh                                                 |
| Boot select                | nice                                           |
| Battery                    | nice                                      |
| Power Profile              | meh                                                 |
| Restart required           | ??                                                  |
| Speech Recognition         | great idea                                          |
| Network Speed              | meh                                                 |
| Update required            | ??                                                  |
| Bluetooth                  | good idea                                           |
| Network Interfaces         | pointless                                           |
| Microphone used            | implementation is a bit sketchy and polling based, but otherwise fine|
| Bash commands              | got                                                 |
| Camera used                | got                                                 |
| SystemD                    | good idea                                           |
| Gamepad Used               | good idea                                           |
| Docker                     | good idea                                           |
| Temperature                | meh                                                 |
| GPIO (inputs, outputs)     | NA                                                  |
| WiFi                       | meh                                                 |
| IR Remote                  | NA                                                  |
| Webcam show                | implementation won't work                           |
| Keyboard Hotkeys           | got && their implementation won't work                           |
| Notify                     | got                                                 |
| Disk IO                    |                                                     |
| Open URL/File (xdg_open)   | good idea                                           |
| Send Keys                  | implementation is X11 - more of a kdeconnect sort of thing anyway                              |
| Statistics                 |                                                     |
| Mouse control              | implementation is X11                               |
| Disk/Mounts usage          |                                                     |
| Media Controls             | really nice                                                |
| Fullscreen                 | implementation won't work                           |
| Screen On/Off              | implementation won't work                           |
| Screenshot Show            | implementation won't work                           |
| Audio Select (microphone, speaker) |                                            |
| Display Variable           | meh          |
| Brightness                 | their implementation won't work                           |
| Idle time                  | their implementation is bad and won't work                           |
| Keep Alive                 | got &&  their implementation won't work                           |
| Steam                      |                                                     |

---

**Reply by D3SOX** [reply]
I also had to tinker a little bit to get it working. This is my configuration now
```yaml
modules:
#- active_window (only x11)
#- audio_select (might want)
- battery
- bluetooth
- camera_used
#- idle (waiting for kde integration)
#- keep_alive (only x11)
- media
- logging_level
- microphone_used
#- network (might want)
- notify
- restart
- shutdown
- speaker_used
- suspend
- update
#- wifi (might want)
exclude:
- audio_select
- bash
- battery
- boot_select
- brightness
- fullscreen
- gpio
- gpu
- idle
- inference_time
- ir_remote
- keep_alive
- keyboard_hotkeys
- media
- mouse
- network
- notify
- power_profile
- restful
- screen_onoff
- screenshot
- send_keys
- speech_recognition
- systemd
- webcam
- xdg_open
custom_modules:
- https://raw.githubusercontent.com/D3SOX/lnxlink-modules/master/kde_screens_onoff.py
```

My setup is now using both components from LNXLink and Kiot. I would prefer to only use Kiot long term so having the features above I use and the ones you noted as good ideas would be great
